### ISSUE TITLE
bugfix: Release - 20012024

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/auth-module#11]
- [x] Label Is not showing  in checkUserExist page.
    Solution: 
![img](https://github.com/wrappid/auth-module/assets/89157406/9ac5ccd5-5a56-44db-a191-5b95d96dbe89)

- [ ] Login with OTP not working - page not rendering
- [ ] Reset password with not working - page not rendering
- [x] white blank space in login page 
- [ ] After successfully login must land on dashboard page

**Comment by irkfaisal** [comment]
issue has been solved while working on delivery oriented related issue
