### ISSUE TITLE
Log in Issue

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/auth-module#79]
- [ ] one user can create 2 different id one by using phone number and another using email id . so i think after login with any of them user should go to profile page and have to fill neccesery details.
- [ ] when trying to change something from the middle at the time of login the cursor automatically goes to right all the time.
- [ ] In log in page the password view icon colour is low .

**Comment by techoneel** [comment]
https://github.com/wrappid/auth-module/issues/129
