### ISSUE TITLE
Incorrect masking of user Email ID

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/auth-module#80]
Describe the bug
When an user enters their email ID on the landing page of stageapp.rxefy.com, on the next page, email masking is wrong.
(Stageapp Version 0.7.11)

To Reproduce

Go to 'http://stageapp.rxefy.com/'
Click on 'Enter Your Registered Email ID or unregistered Email ID'
Click Continue 'On the Next page, email masking is wrong'
See error
Expected behavior
If email ID is '[abcd@gmail.com](mailto:abcd@gmail.com)'
Expected Output is: '[aXXd@gXXXX.com](mailto:aXXd@gXXXX.com)'
Actual Output is: 'aXXX@g@gXXilXc'

Screenshots
Screenshot 2023-04-21 at 10-48-47 Rxefy

Desktop:

OS: [Fedora Workstation 38]
Browser [Mozilla Firefox v112.0 64 bit]
Version [ v112.0]
Smartphone:

Device: [Xiaomi-Redmi 6 pro]
OS: [e.g. Android 12 Custom Rom]
Browser [Brave Browser]
Version [Brave 1.49.132, based on Chromium 111.0.5563.147]
Additional context
NA

**Comment by techoneel** [comment]
closing this issue as of now
